name: S3_Upload

on:
  push:
    branches: ['master']

jobs:
  build-node:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Install aws cli
        uses: chrislennon/action-aws-cli@v1.1

      - name: Upload static files
        run: aws s3 sync ${{ secrets.SOURCE }} ${{ secrets.BUCKET }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
